### ISSUE TITLE
Please consider yanking v1.1

### ISSUE THREAD

**Issue by sebadob** [kennytm/parse-size#4]
Please consider yanking `v1.1.` and re-release as `v2.0.0`.

With version 1.1 you bumped the MSRV to 1.81 which is a breaking change.   
Publishing a `v2.0.0` instead would be the better solution. 

The v1.1 will just break a lot of builds and pipelines (like mine now).

**Comment by kennytm** [comment]
sorry won't fix

As described in https://doc.rust-lang.org/cargo/reference/semver.html#env-new-rust, 

> It is generally recommended to treat this as a minor change, rather than as a major change, for various reasons.

We are also basically adapting [`jiff`'s MSRV policy](https://github.com/BurntSushi/jiff?tab=readme-ov-file#minimum-rust-version-policy)

>  The policy is that the minimum Rust version required to use this crate can be increased in minor version updates. For example, if jiff 1.0 requires Rust 1.20.0, then jiff 1.0.z for all values of z will also require Rust 1.20.0 or newer. **However, jiff 1.y for y > 0 may require a newer minimum version of Rust.**

If for whatever reason you can't upgrade the Rust compiler version you can lock the `parse-size` version with

```
[dependencies]
parse-size = "=1.0.0"
```
